use std::{fs, path::Path, time::Duration};

use super::*;

/// A fake home directory with the XDG layout the lookup reads.
pub(in crate::app) struct Fixture {
    pub dir: tempfile::TempDir,
}

impl Fixture {
    pub fn new(kde: bool) -> (Self, Env) {
        let dir = tempfile::tempdir().unwrap();
        let fixture = Self { dir };
        let env = fixture.env(kde);
        (fixture, env)
    }

    /// A fresh environment over this fixture's folders.
    pub fn env(&self, kde: bool) -> Env {
        let home = self.dir.path().join("home");
        Env {
            config_home: home.join(".config"),
            data_home: home.join(".local/share"),
            data_dirs: vec![self.dir.path().join("usr/share")],
            home,
            kde,
            ..Env::default()
        }
    }

    pub fn write(&self, relative: &str, content: impl AsRef<[u8]>) {
        let path = self.dir.path().join(relative);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, content).unwrap();
    }

    pub fn path(&self, relative: &str) -> PathBuf {
        self.dir.path().join(relative)
    }

    /// A valid PNG of one colour.
    pub fn png(&self, relative: &str, rgba: [u8; 4], size: u32) {
        let path = self.path(relative);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        image::RgbaImage::from_pixel(size, size, image::Rgba(rgba))
            .save(path)
            .unwrap();
    }

    pub fn svg(&self, relative: &str, fill: &str) {
        self.write(
            relative,
            format!(
                r#"<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><rect width="16" height="16" fill="{fill}"/></svg>"#
            ),
        );
    }
}

const HOME: &str = "home/";

/// Assets and CSS in the shape kde-gtk-config is believed to write.
fn kde_gtk_config(fx: &Fixture, version: &str) {
    let dir = format!("{HOME}.config/{version}");
    for name in [
        "close",
        "close-hover",
        "close-active",
        "close-backdrop",
        "minimize",
        "minimize-hover",
        "maximize",
        "maximize-hover",
        "restore",
        "restore-hover",
    ] {
        fx.png(
            &format!("{dir}/assets/titlebutton-{name}.png"),
            [1, 2, 3, 255],
            20,
        );
    }
    fx.png(
        &format!("{dir}/assets/titlebutton-close@2.png"),
        [1, 2, 3, 255],
        40,
    );
    fx.write(
        &format!("{dir}/window_decorations.css"),
        "/* Generated by kde-gtk-config */\r\n\
         .titlebar button.titlebutton.close, headerbar button.titlebutton.close {\r\n\
           background-image: -gtk-scaled(url('assets/titlebutton-close.png'), url('assets/titlebutton-close@2.png'));\r\n\
         }\r\n\
         .titlebar button.titlebutton.close:hover { background-image: url(\"assets/titlebutton-close-hover.png\"); }\r\n\
         .titlebar button.titlebutton.close:active { background-image: url(assets/titlebutton-close-active.png); }\r\n\
         .titlebar button.titlebutton.close:backdrop { background-image: url(\"assets/titlebutton-close-backdrop.png\"); }\r\n\
         .titlebar button.titlebutton.minimize { background-image: url(\"assets/titlebutton-minimize.png\"); }\r\n\
         .titlebar button.titlebutton.minimize:hover { background-image: url(\"assets/titlebutton-minimize-hover.png\"); }\r\n\
         .titlebar button.titlebutton.maximize { background-image: url(\"assets/titlebutton-maximize.png\"); }\r\n\
         .titlebar button.titlebutton.maximize:hover { background-image: url(\"assets/titlebutton-maximize-hover.png\"); }\r\n\
         .maximized .titlebar button.titlebutton.maximize { background-image: url(\"assets/titlebutton-restore.png\"); }\r\n\
         .maximized .titlebar button.titlebutton.maximize:hover { background-image: url(\"assets/titlebutton-restore-hover.png\"); }\r\n\
         button.titlebutton { padding: 0; }\r\n",
    );
    fx.write(
        &format!("{dir}/gtk.css"),
        "@import url(\"window_decorations.css\");\n",
    );
}

fn path_of(resolved: &Resolved, kind: Kind, state: State, fx: &Fixture) -> String {
    resolved
        .path(kind, state)
        .map(|p| {
            p.strip_prefix(fx.dir.path())
                .unwrap()
                .to_string_lossy()
                .into_owned()
        })
        .unwrap_or_default()
}

fn resolve_env(env: &Env) -> Option<Resolved> {
    resolve(env, &Probe::new(env))
}

#[test]
fn kde_gtk_config_css_resolves_every_button_and_state() {
    let (fx, env) = Fixture::new(true);
    kde_gtk_config(&fx, "gtk-3.0");
    fx.write(
        "home/.config/kdeglobals",
        "[Colors:Header]\r\nForegroundNormal=252,252,252\r\nForegroundInactive=161,169,177\r\n",
    );
    let resolved = resolve_env(&env).expect("kde-gtk-config assets");
    assert_eq!(resolved.source, Source::KdeGtkConfig);
    let p = |kind, state| path_of(&resolved, kind, state, &fx);
    let dir = "home/.config/gtk-3.0/assets/titlebutton-";
    assert_eq!(p(Kind::Close, State::Normal), format!("{dir}close.png"));
    assert_eq!(
        p(Kind::Close, State::Hover),
        format!("{dir}close-hover.png")
    );
    assert_eq!(
        p(Kind::Close, State::Active),
        format!("{dir}close-active.png")
    );
    assert_eq!(
        p(Kind::Close, State::Backdrop),
        format!("{dir}close-backdrop.png")
    );
    assert_eq!(
        p(Kind::Minimize, State::Normal),
        format!("{dir}minimize.png")
    );
    assert_eq!(
        p(Kind::Minimize, State::Hover),
        format!("{dir}minimize-hover.png")
    );
    assert_eq!(
        p(Kind::Maximize, State::Normal),
        format!("{dir}maximize.png")
    );
    assert_eq!(
        p(Kind::Maximize, State::Hover),
        format!("{dir}maximize-hover.png")
    );
    assert_eq!(p(Kind::Restore, State::Normal), format!("{dir}restore.png"));
    assert_eq!(
        p(Kind::Restore, State::Hover),
        format!("{dir}restore-hover.png")
    );
    assert_eq!(p(Kind::Minimize, State::Active), "");

    // `-gtk-scaled` offers the 2x image on a HiDPI display.
    let at = |ppp| {
        resolved
            .pick(Kind::Close, State::Normal, ppp)
            .unwrap()
            .asset
            .clone()
    };
    assert!(at(1.0).path.ends_with("titlebutton-close.png") && at(1.0).scale == 1);
    assert!(at(2.0).path.ends_with("titlebutton-close@2.png") && at(2.0).scale == 2);
    assert!(at(1.5).path.ends_with("titlebutton-close@2.png"));
    assert_eq!(
        resolved.tints,
        Tints {
            active: Some([252, 252, 252]),
            inactive: Some([161, 169, 177]),
            ..Tints::default()
        }
    );
}

#[test]
fn missing_states_fall_back_to_the_normal_image_with_a_highlight() {
    let (fx, env) = Fixture::new(true);
    kde_gtk_config(&fx, "gtk-3.0");
    let resolved = resolve_env(&env).unwrap();
    // Own image: no highlight.
    let hover = resolved.pick(Kind::Close, State::Hover, 1.0).unwrap();
    assert!(hover.asset.path.ends_with("titlebutton-close-hover.png"));
    assert_eq!(hover.highlight, Highlight::None);
    // Minimize has no pressed image: the hover one, highlighted.
    let pressed = resolved.pick(Kind::Minimize, State::Active, 1.0).unwrap();
    assert!(
        pressed
            .asset
            .path
            .ends_with("titlebutton-minimize-hover.png")
    );
    assert_eq!(pressed.highlight, Highlight::Pressed);
    // Maximize has no backdrop image: the normal one, dimmed.
    let backdrop = resolved.pick(Kind::Maximize, State::Backdrop, 1.0).unwrap();
    assert!(backdrop.asset.path.ends_with("titlebutton-maximize.png") && backdrop.dim);
    // A theme with no hover image at all.
    let (fx2, env2) = Fixture::new(true);
    fx2.png("home/.config/gtk-3.0/a.png", [0; 4], 4);
    fx2.write(
        "home/.config/gtk-3.0/window_decorations.css",
        ".titlebar button.close, .titlebar button.minimize, .titlebar button.maximize { background-image: url(a.png) }",
    );
    let plain = resolve_env(&env2).unwrap();
    let hover = plain.pick(Kind::Close, State::Hover, 1.0).unwrap();
    assert!(hover.asset.path.ends_with("a.png") && hover.highlight == Highlight::Hover);
    // No restore image: the caller draws its own glyph for it.
    assert!(plain.pick(Kind::Restore, State::Normal, 1.0).is_none());
}

#[test]
fn gtk_4_assets_are_used_when_gtk_3_has_none() {
    let (fx, env) = Fixture::new(true);
    kde_gtk_config(&fx, "gtk-4.0");
    fx.write(
        "home/.config/gtk-3.0/window_decorations.css",
        "button { color: red }",
    );
    let resolved = resolve_env(&env).unwrap();
    assert_eq!(resolved.source, Source::KdeGtkConfig);
    assert!(
        resolved
            .path(Kind::Close, State::Normal)
            .unwrap()
            .to_string_lossy()
            .contains("gtk-4.0")
    );
}

#[test]
fn selector_shapes_from_breeze_gtk_and_gtk4_themes() {
    let cases = [
        (
            ".titlebar button.titlebutton.close",
            Some((Kind::Close, State::Normal)),
        ),
        (
            "headerbar button.titlebutton.minimize:hover",
            Some((Kind::Minimize, State::Hover)),
        ),
        (
            "window.csd > .titlebar .titlebutton.maximize:active",
            Some((Kind::Maximize, State::Active)),
        ),
        (
            "windowcontrols button.close:backdrop",
            Some((Kind::Close, State::Backdrop)),
        ),
        (
            "window.maximized .titlebar button.maximize",
            Some((Kind::Restore, State::Normal)),
        ),
        (
            "window:not(.maximized) .titlebar button.maximize",
            Some((Kind::Maximize, State::Normal)),
        ),
        (
            "button.titlebutton.maximize:checked",
            Some((Kind::Restore, State::Normal)),
        ),
        (
            ".titlebar button.titlebutton.restore:hover",
            Some((Kind::Restore, State::Hover)),
        ),
        // Not title buttons.
        ("button.close", None),
        (".titlebar button", None),
        (".titlebar button.close:disabled", None),
        (".titlebar button.close:backdrop:hover", None),
        ("", None),
        ("{{{", None),
    ];
    for (selector, expected) in cases {
        assert_eq!(classify(selector), expected, "{selector}");
    }
}

#[test]
fn css_reader_follows_imports_uses_later_rules_and_survives_odd_input() {
    let (fx, env) = Fixture::new(true);
    for n in ["a", "b", "c", "d"] {
        fx.png(&format!("home/.config/gtk-3.0/{n}.png"), [9, 9, 9, 255], 4);
    }
    fx.write(
        "home/.config/gtk-3.0/gtk.css",
        "@define-color fg #fff;\n@import 'window_decorations.css';\n@import url(\"gtk.css\");\n\
         @media (min-width: 1px) { .titlebar button.close { background-image: url(a.png) } }\n\
         .titlebar button.minimize { background-image: image(url(\"b.png\"), linear-gradient(red, blue)); }\n\
         /* .titlebar button.maximize { background-image: url(a.png) } */\n\
         .titlebar button.maximize { background: url(\"c.png\") no-repeat center; border: 1px solid }\n\
         .titlebar button.maximize { -gtk-icon-source: none; }\n",
    );
    fx.write(
        "home/.config/gtk-3.0/window_decorations.css",
        "@import url(\"../outside.css\");\n.titlebar button.close { background-image: url(d.png) }\n\
         .titlebar button.close { background-image: url(missing.png) }\n",
    );
    let resolved = resolve_env(&env).unwrap();
    let p = |kind| path_of(&resolved, kind, State::Normal, &fx);
    // The unreadable import and the missing file are skipped; `d.png` stays.
    assert!(p(Kind::Close).ends_with("d.png"));
    assert!(p(Kind::Minimize).ends_with("b.png"));
    assert!(p(Kind::Maximize).ends_with("c.png"));
}

#[test]
fn malformed_css_is_not_found_and_does_not_panic() {
    let junk = [
        "",
        "{",
        "}}}}",
        ".titlebar button.close { background-image: url(",
        ".titlebar button.close { background-image: url(\"unterminated",
        "@import",
        "@import url(",
        "/* never closed",
        ".a, , .b { ; ; ; }",
        "\u{0}\u{1}\u{2}",
        "button.close:hover:hover:::: {{ }} }",
    ];
    for text in junk {
        let (fx, env) = Fixture::new(true);
        fx.write("home/.config/gtk-3.0/window_decorations.css", text);
        assert!(resolve_env(&env).is_none(), "{text:?}");
    }
    // Invalid UTF-8 is simply unreadable.
    let (fx, env) = Fixture::new(true);
    fx.write(
        "home/.config/gtk-3.0/window_decorations.css",
        [0xff, 0xfe, 0x00],
    );
    assert!(resolve_env(&env).is_none());
}

#[test]
fn files_outside_the_theme_dirs_or_too_large_are_ignored() {
    let (fx, env) = Fixture::new(true);
    fx.png("outside/close.png", [0; 4], 4);
    fx.png("home/.config/gtk-3.0/ok.png", [0; 4], 4);
    fx.write(
        "home/.config/gtk-3.0/huge.png",
        vec![0u8; MAX_FILE_BYTES as usize + 1],
    );
    fx.write("home/.config/gtk-3.0/notes.txt", "x");
    fx.write(
        "home/.config/gtk-3.0/window_decorations.css",
        ".titlebar button.close { background-image: url(../../../outside/close.png) }\n\
         .titlebar button.minimize { background-image: url(file:///etc/passwd.png) }\n\
         .titlebar button.maximize { background-image: url(huge.png) }\n",
    );
    assert!(resolve_env(&env).is_none());
    fx.write(
        "home/.config/gtk-3.0/window_decorations.css",
        ".titlebar button.close { background-image: url(ok.png) }\n\
         .titlebar button.minimize { background-image: url(notes.txt) }\n\
         .titlebar button.maximize { background-image: url(ok.png) }\n",
    );
    assert!(resolve_env(&env).is_none());
    // A stylesheet over the cap is not read.
    let (fx, env) = Fixture::new(true);
    fx.png("home/.config/gtk-3.0/ok.png", [0; 4], 4);
    let mut css = String::from(
        ".titlebar button.close, .titlebar button.minimize, .titlebar button.maximize { background-image: url(ok.png) }\n",
    );
    css.push_str(&" ".repeat(MAX_FILE_BYTES as usize));
    fx.write("home/.config/gtk-3.0/window_decorations.css", css);
    assert!(resolve_env(&env).is_none());
}

fn gtk_theme(fx: &Fixture, base: &str, name: &str) {
    let dir = format!("{base}/{name}/gtk-3.0");
    for n in ["close", "min", "max"] {
        fx.png(&format!("{dir}/assets/{n}.png"), [5, 5, 5, 255], 8);
    }
    fx.write(
        &format!("{dir}/gtk.css"),
        ".titlebar button.titlebutton.close { background-image: url(\"assets/close.png\") }\n\
         .titlebar button.titlebutton.minimize { background-image: url(\"assets/min.png\") }\n\
         .titlebar button.titlebutton.maximize { background-image: url(\"assets/max.png\") }\n",
    );
}

#[test]
fn gtk_theme_is_found_by_settings_ini_in_data_home_before_data_dirs() {
    let (fx, env) = Fixture::new(false);
    fx.write(
        "home/.config/gtk-3.0/settings.ini",
        "[Settings]\r\ngtk-theme-name=Fancy\r\ngtk-icon-theme-name=Nothing\r\n",
    );
    gtk_theme(&fx, "usr/share/themes", "Fancy");
    let resolved = resolve_env(&env).unwrap();
    assert_eq!(resolved.source, Source::GtkTheme);
    assert!(
        path_of(&resolved, Kind::Close, State::Normal, &fx).starts_with("usr/share/themes/Fancy")
    );
    gtk_theme(&fx, "home/.local/share/themes", "Fancy");
    let resolved = resolve_env(&env).unwrap();
    assert!(
        path_of(&resolved, Kind::Close, State::Normal, &fx)
            .starts_with("home/.local/share/themes/Fancy")
    );
}

#[test]
fn gtk_theme_name_falls_back_to_gsettings_and_dark_variant_applies() {
    let (fx, mut env) = Fixture::new(false);
    env.gsettings_gtk_theme = Some("Dusk".into());
    gtk_theme(&fx, "home/.themes", "Dusk");
    assert_eq!(resolve_env(&env).unwrap().source, Source::GtkTheme);
    fx.png("home/.themes/Dusk/gtk-3.0/assets/dark-close.png", [0; 4], 4);
    fx.write(
        "home/.themes/Dusk/gtk-3.0/gtk-dark.css",
        ".titlebar button.titlebutton.close { background-image: url(assets/dark-close.png) }",
    );
    // Not preferred: the light image.
    let resolved = resolve_env(&env).unwrap();
    assert!(
        resolved
            .path(Kind::Close, State::Normal)
            .unwrap()
            .ends_with("assets/close.png")
    );
    fx.write(
        "home/.config/gtk-3.0/settings.ini",
        "[Settings]\ngtk-application-prefer-dark-theme=1\n",
    );
    let resolved = resolve_env(&env).unwrap();
    assert!(
        resolved
            .path(Kind::Close, State::Normal)
            .unwrap()
            .ends_with("assets/dark-close.png")
    );
}

fn icon_theme(fx: &Fixture, name: &str, index: &str) {
    fx.write(&format!("usr/share/icons/{name}/index.theme"), index);
}

#[test]
fn icon_theme_lookup_follows_inherits_picks_the_nearest_size_and_falls_back_to_hicolor() {
    let (fx, mut env) = Fixture::new(true);
    fx.write(
        "home/.config/kdeglobals",
        "[Icons]\nTheme=Child\n[Colors:Header]\nForegroundNormal=#fcfcfc\n[WM]\nactiveForeground=1,2,3\n",
    );
    icon_theme(
        &fx,
        "Child",
        "[Icon Theme]\r\nName=Child\r\nInherits=Parent,Other\r\nDirectories=actions/16,actions/48\r\n\
         [actions/16]\nSize=16\nType=Fixed\n[actions/48]\nSize=48\nType=Fixed\n",
    );
    icon_theme(
        &fx,
        "Parent",
        "[Icon Theme]\nInherits=\nDirectories=actions/scalable,actions/22\n\
         [actions/scalable]\nSize=16\nMinSize=8\nMaxSize=512\nType=Scalable\n\
         [actions/22]\nSize=22\nType=Fixed\n",
    );
    icon_theme(
        &fx,
        "hicolor",
        "[Icon Theme]\nDirectories=actions/16\n[actions/16]\nSize=16\nType=Fixed\n",
    );
    // Child has the close and minimize icons at two sizes: the 16 px one wins.
    for name in ["window-close-symbolic", "window-minimize-symbolic"] {
        fx.svg(
            &format!("usr/share/icons/Child/actions/16/{name}.svg"),
            "#232629",
        );
        fx.svg(
            &format!("usr/share/icons/Child/actions/48/{name}.svg"),
            "#232629",
        );
    }
    // Parent has maximize at 22 and a scalable one: scalable (distance 0) wins.
    fx.svg(
        "usr/share/icons/Parent/actions/22/window-maximize-symbolic.svg",
        "#232629",
    );
    fx.svg(
        "usr/share/icons/Parent/actions/scalable/window-maximize-symbolic.svg",
        "#232629",
    );
    // Restore only exists in hicolor.
    fx.svg(
        "usr/share/icons/hicolor/actions/16/window-restore-symbolic.svg",
        "#232629",
    );
    let resolved = resolve_env(&env).unwrap();
    assert_eq!(resolved.source, Source::IconTheme);
    let p = |kind| path_of(&resolved, kind, State::Normal, &fx);
    assert_eq!(
        p(Kind::Close),
        "usr/share/icons/Child/actions/16/window-close-symbolic.svg"
    );
    assert_eq!(
        p(Kind::Minimize),
        "usr/share/icons/Child/actions/16/window-minimize-symbolic.svg"
    );
    assert_eq!(
        p(Kind::Maximize),
        "usr/share/icons/Parent/actions/scalable/window-maximize-symbolic.svg"
    );
    assert_eq!(
        p(Kind::Restore),
        "usr/share/icons/hicolor/actions/16/window-restore-symbolic.svg"
    );
    assert!(
        resolved
            .pick(Kind::Close, State::Normal, 1.0)
            .unwrap()
            .asset
            .symbolic
    );
    // Header colours win over [WM].
    assert_eq!(resolved.tints.active, Some([252, 252, 252]));

    // GTK desktops name the icon theme in settings.ini, then gsettings.
    env.kde = false;
    fx.write(
        "home/.config/gtk-3.0/settings.ini",
        "[Settings]\ngtk-icon-theme-name=Parent\n",
    );
    let resolved = resolve_env(&env);
    assert!(
        resolved.is_none(),
        "Parent lacks close and minimize: {resolved:?}"
    );
    fx.write(
        "home/.config/gtk-3.0/settings.ini",
        "[Settings]\ngtk-icon-theme-name=Child\n",
    );
    assert!(resolve_env(&env).is_some());
}

#[test]
fn inherits_cycles_and_odd_theme_names_are_harmless() {
    let (fx, mut env) = Fixture::new(false);
    env.gsettings_icon_theme = Some("A".into());
    icon_theme(
        &fx,
        "A",
        "[Icon Theme]\nInherits=B\nDirectories=x\n[x]\nSize=16\n",
    );
    icon_theme(
        &fx,
        "B",
        "[Icon Theme]\nInherits=A,../../etc\nDirectories=x\n[x]\nSize=16\n",
    );
    assert!(resolve_env(&env).is_none());
    icon_theme(&fx, "A", "garbage \u{0}\n[[[");
    assert!(resolve_env(&env).is_none());
}

#[test]
fn lookup_order_is_kde_then_gtk_theme_then_icons_then_nothing() {
    let (fx, mut env) = Fixture::new(true);
    fx.write(
        "home/.config/gtk-3.0/settings.ini",
        "[Settings]\ngtk-theme-name=Fancy\n",
    );
    gtk_theme(&fx, "usr/share/themes", "Fancy");
    icon_theme(&fx, "breeze", "[Icon Theme]\nDirectories=a\n[a]\nSize=16\n");
    for name in ["minimize", "maximize", "restore", "close"] {
        fx.svg(
            &format!("usr/share/icons/breeze/a/window-{name}-symbolic.svg"),
            "#000",
        );
    }
    // KDE with no decoration assets: the GTK theme.
    assert_eq!(resolve_env(&env).unwrap().source, Source::GtkTheme);
    // With them: kde-gtk-config wins.
    kde_gtk_config(&fx, "gtk-3.0");
    assert_eq!(resolve_env(&env).unwrap().source, Source::KdeGtkConfig);
    // Other desktops never look at the kde-gtk-config files.
    env.kde = false;
    assert_eq!(resolve_env(&env).unwrap().source, Source::GtkTheme);
    // A GTK theme that names no usable images falls through to the icon theme.
    fx.write(
        "usr/share/themes/Fancy/gtk-3.0/gtk.css",
        "button { color: red }",
    );
    fx.write(
        "home/.config/gtk-3.0/settings.ini",
        "[Settings]\ngtk-theme-name=Fancy\ngtk-icon-theme-name=breeze\n",
    );
    assert_eq!(resolve_env(&env).unwrap().source, Source::IconTheme);
    // Nothing installed: the built-in glyphs.
    assert!(resolve_env(&Env::default()).is_none());
    let (_empty, empty_env) = Fixture::new(true);
    assert!(resolve_env(&empty_env).is_none());
}

#[test]
fn kwinrc_button_order() {
    use super::super::chrome::{ButtonLayout, WindowButton::*};
    let layout = |text| ButtonLayout::parse_kwin(text);
    // KWin's own defaults, and a file without the group.
    assert_eq!(
        layout("[org.kde.kdecoration2]\nButtonsOnLeft=MS\nButtonsOnRight=HIAX\n"),
        Some(ButtonLayout::default())
    );
    assert_eq!(
        layout("[General]\nfoo=bar\n"),
        Some(ButtonLayout::default())
    );
    assert_eq!(layout(""), Some(ButtonLayout::default()));
    // macOS-like, CRLF, with unknown letters (menu, help, keep above, shade).
    assert_eq!(
        layout("[org.kde.kdecoration2]\r\nButtonsOnLeft=XIA\r\nButtonsOnRight=FBLH\r\n"),
        Some(ButtonLayout {
            left: vec![Close, Minimize, Maximize],
            right: vec![]
        })
    );
    assert_eq!(
        layout("[org.kde.kdecoration2]\nButtonsOnLeft=MF\nButtonsOnRight=IAX\nBorderSize=Normal\n"),
        Some(ButtonLayout {
            left: vec![],
            right: vec![Minimize, Maximize, Close]
        })
    );
    // One key only: the other side keeps KWin's default.
    assert_eq!(
        layout("[org.kde.kdecoration2]\nButtonsOnLeft=X\n"),
        Some(ButtonLayout {
            left: vec![Close],
            right: vec![Minimize, Maximize, Close]
        })
    );
    // Keys in other groups do not count; lowercase letters are not buttons.
    assert_eq!(
        layout(
            "[Windows]\nButtonsOnRight=X\n[org.kde.kdecoration2]\nButtonsOnRight=iax\nButtonsOnLeft=\n"
        ),
        None
    );
    assert_eq!(
        layout("[org.kde.kdecoration2]\nButtonsOnLeft=\nButtonsOnRight=\n"),
        None
    );
    assert!(
        desktop_is("KDE", "KDE")
            && desktop_is("ubuntu:GNOME", "gnome")
            && !desktop_is("X-KDE", "KDE")
    );
}

#[test]
fn colours_parse_from_kdeglobals() {
    let sample = "[ColorEffects:Disabled]\nColor=56,56,56\n\
        [Colors:Header]\nBackgroundNormal=239,240,241,255\nForegroundNormal=35,38,41\nForegroundInactive=127, 140, 141\n\
        [WM]\nactiveForeground=71,80,87\ninactiveForeground=189,195,199\n";
    assert_eq!(
        Tints::from_kdeglobals(sample),
        Tints {
            active: Some([35, 38, 41]),
            inactive: Some([127, 140, 141]),
            ..Tints::default()
        }
    );
    // Without a header group, [WM] is used.
    assert_eq!(
        Tints::from_kdeglobals(
            "[WM]\nactiveForeground=71,80,87\r\ninactiveForeground=189,195,199\r\n"
        ),
        Tints {
            active: Some([71, 80, 87]),
            inactive: Some([189, 195, 199]),
            ..Tints::default()
        }
    );
    assert_eq!(
        Tints::from_kdeglobals("[Colors:Header]\nForegroundNormal=oops\n"),
        Tints::default()
    );
    assert_eq!(parse_color("#FFaa00"), Some([255, 170, 0]));
    assert_eq!(parse_color("1,2,3,4"), Some([1, 2, 3]));
    for bad in ["", "1,2", "300,0,0", "#12", "red", "1,2,3,4,5"] {
        assert_eq!(parse_color(bad), None, "{bad}");
    }
    // A dark KDE header colour is unreadable on Xuan's dark title bar: use Xuan's own.
    let tints = Tints {
        active: Some([35, 38, 41]),
        inactive: Some([250, 250, 250]),
        ..Tints::default()
    };
    let bg = Color32::from_gray(30);
    let fallback = Color32::from_gray(200);
    assert_eq!(tints.color(false, bg, fallback), fallback);
    assert_eq!(tints.color(true, bg, fallback), Color32::from_gray(250));
    assert_eq!(Tints::default().color(false, bg, fallback), fallback);
}

fn set_modified(path: &Path, seconds_ahead: u64) {
    let file = fs::OpenOptions::new().write(true).open(path).unwrap();
    file.set_modified(SystemTime::now() + Duration::from_secs(seconds_ahead))
        .unwrap();
}

#[test]
fn changed_files_reload_the_theme_but_only_when_the_interval_has_passed() {
    let (fx, env) = Fixture::new(true);
    kde_gtk_config(&fx, "gtk-3.0");
    let mut theme = WindowTheme::new(env);
    let start = Instant::now();
    assert_eq!(theme.generation, 1);
    let first = theme
        .resolved()
        .unwrap()
        .pick(Kind::Close, State::Normal, 1.0)
        .unwrap()
        .asset
        .clone();

    // Unchanged files: no reload, however often it is asked.
    theme.refresh(start + RECHECK * 2);
    assert_eq!(theme.generation, 1);

    // Plasma rewrites an asset: same path, new mtime. Too soon to look.
    let asset = fx.path("home/.config/gtk-3.0/assets/titlebutton-close.png");
    set_modified(&asset, 100);
    theme.refresh(start + RECHECK * 2 + Duration::from_millis(500));
    assert_eq!(theme.generation, 1);
    theme.refresh(start + RECHECK * 4);
    assert_eq!(theme.generation, 2);
    let second = theme
        .resolved()
        .unwrap()
        .pick(Kind::Close, State::Normal, 1.0)
        .unwrap()
        .asset
        .clone();
    assert_eq!(first.path, second.path);
    assert_ne!(first.stamp, second.stamp);
    // The texture is keyed by the new mtime, so the old texture is not reused.
    assert_ne!(
        TextureKey::new(&first, 1.0, None),
        TextureKey::new(&second, 1.0, None)
    );
    assert_ne!(
        TextureKey::new(&second, 1.0, None),
        TextureKey::new(&second, 2.0, None)
    );
    assert_eq!(
        TextureKey::new(&second, 1.0, None),
        TextureKey::new(&second, 1.0, None)
    );

    // The decoration changes: the CSS now names other files.
    fx.png(
        "home/.config/gtk-3.0/assets/new-close.png",
        [7, 7, 7, 255],
        12,
    );
    let css = fx.path("home/.config/gtk-3.0/window_decorations.css");
    let text = fs::read_to_string(&css)
        .unwrap()
        .replace("titlebutton-close.png", "new-close.png");
    fs::write(&css, text).unwrap();
    set_modified(&css, 200);
    theme.refresh(start + RECHECK * 6);
    assert_eq!(theme.generation, 3);
    assert!(
        theme
            .resolved()
            .unwrap()
            .path(Kind::Close, State::Normal)
            .unwrap()
            .ends_with("new-close.png")
    );

    // A better source appearing later is noticed too: delete everything, then add it back.
    let (fx2, env2) = Fixture::new(true);
    let mut empty = WindowTheme::new(env2);
    assert!(empty.resolved().is_none());
    kde_gtk_config(&fx2, "gtk-3.0");
    empty.refresh(Instant::now() + RECHECK * 2);
    assert!(empty.resolved().is_some());
}

#[test]
fn png_and_svg_rasterise_at_the_display_scale_and_symbolic_icons_take_the_tint() {
    let (fx, _) = Fixture::new(false);
    fx.png("a.png", [10, 20, 30, 255], 20);
    fx.svg("a.svg", "#ff0000");
    let png = rasterise(&fs::read(fx.path("a.png")).unwrap(), false, 2.0, None).unwrap();
    assert_eq!(png.size, [20, 20]);
    assert_eq!(png.pixels[0], Color32::from_rgb(10, 20, 30));
    let svg = fs::read(fx.path("a.svg")).unwrap();
    assert_eq!(rasterise(&svg, true, 1.0, None).unwrap().size, [16, 16]);
    let hidpi = rasterise(&svg, true, 2.0, None).unwrap();
    assert_eq!(hidpi.size, [32, 32]);
    let tinted = rasterise(&svg, true, 1.0, Some(Color32::from_rgb(1, 2, 3))).unwrap();
    assert_eq!(tinted.pixels[0], Color32::from_rgb(1, 2, 3));
    // Malformed, truncated and oversized inputs are just not images.
    assert!(rasterise(b"<svg", true, 1.0, None).is_none());
    assert!(rasterise(b"not an svg at all", true, 1.0, None).is_none());
    assert!(rasterise(b"\x89PNG\r\n\x1a\n", false, 1.0, None).is_none());
    assert!(rasterise(&[], false, 1.0, None).is_none());
    let big = r#"<svg xmlns="http://www.w3.org/2000/svg" width="600" height="600"/>"#;
    assert!(rasterise(big.as_bytes(), true, 1.0, None).is_none());
}

#[test]
fn textures_are_cached_per_asset_and_a_broken_asset_is_remembered() {
    let (fx, env) = Fixture::new(false);
    fx.write(
        "home/.config/gtk-3.0/settings.ini",
        "[Settings]\ngtk-theme-name=Fancy\n",
    );
    gtk_theme(&fx, "usr/share/themes", "Fancy");
    // Replace one image with bytes that are not a PNG.
    fx.write("usr/share/themes/Fancy/gtk-3.0/assets/min.png", b"garbage");
    let mut theme = WindowTheme::new(env);
    let ctx = egui::Context::default();
    let ppp = 1.0;
    let assets: Vec<Asset> = [Kind::Close, Kind::Minimize]
        .iter()
        .map(|&k| {
            theme
                .resolved()
                .unwrap()
                .pick(k, State::Normal, ppp)
                .unwrap()
                .asset
                .clone()
        })
        .collect();
    let (id, size) = theme.texture(&ctx, &assets[0], ppp, None).unwrap();
    assert_eq!(size, Vec2::splat(8.0));
    assert_eq!(theme.texture(&ctx, &assets[0], ppp, None).unwrap().0, id);
    assert!(theme.texture(&ctx, &assets[1], ppp, None).is_none());
    assert_eq!(theme.loaded_textures(), 1);
}

#[test]
fn negative_colour_comes_from_the_window_group_then_the_header_group() {
    let both = "[Colors:Header]\nForegroundNegative=1,2,3\n[Colors:Window]\nForegroundNegative=218,68,83\n";
    assert_eq!(Tints::from_kdeglobals(both).negative, Some([218, 68, 83]));
    let header = "[Colors:Header]\r\nForegroundNegative=1,2,3\r\n";
    assert_eq!(Tints::from_kdeglobals(header).negative, Some([1, 2, 3]));
    assert_eq!(
        Tints::from_kdeglobals("[Colors:Window]\nForegroundNegative=x\n").negative,
        None
    );
    assert_eq!(Tints::from_kdeglobals("").negative, None);
    // Absent: a fallback red, not a transparent or white fill.
    assert_eq!(Tints::default().negative_color(), FALLBACK_NEGATIVE);
}

#[test]
fn close_fill_uses_the_negative_colour_for_hover_and_a_darker_one_pressed() {
    let bg = Color32::from_gray(30);
    let tints = Tints {
        negative: Some([200, 20, 40]),
        ..Tints::default()
    };
    let red = Color32::from_rgb(200, 20, 40);
    assert_eq!(tints.close_fill(Highlight::Hover, bg), Some((red, bg)));
    let (pressed, glyph) = tints.close_fill(Highlight::Pressed, bg).unwrap();
    assert_eq!(glyph, bg);
    assert!(pressed.r() < red.r() && pressed.r() > 0);
    assert_eq!(tints.close_fill(Highlight::None, bg), None);
    assert_eq!(
        Tints::default().close_fill(Highlight::Hover, bg),
        Some((FALLBACK_NEGATIVE, bg))
    );
}

#[test]
fn kde_icon_theme_close_hover_takes_the_negative_colour_from_kdeglobals() {
    let (fx, env) = Fixture::new(true);
    fx.write(
        "home/.config/kdeglobals",
        "[Icons]\nTheme=breeze\n[Colors:Window]\nForegroundNegative=218,68,83\n",
    );
    icon_theme(
        &fx,
        "breeze",
        "[Icon Theme]\nDirectories=actions\n[actions]\nSize=16\nType=Fixed\n",
    );
    for name in ["minimize", "maximize", "restore", "close"] {
        fx.svg(
            &format!("usr/share/icons/breeze/actions/window-{name}-symbolic.svg"),
            "#000",
        );
    }
    let resolved = resolve_env(&env).unwrap();
    assert_eq!(resolved.source, Source::IconTheme);
    let hover = resolved.pick(Kind::Close, State::Hover, 1.0).unwrap();
    assert!(hover.asset.symbolic);
    let bg = Color32::from_gray(30);
    assert_eq!(
        resolved.tints.close_fill(hover.highlight, bg),
        Some((Color32::from_rgb(218, 68, 83), bg))
    );
    let pressed = resolved.pick(Kind::Close, State::Active, 1.0).unwrap();
    assert_eq!(pressed.highlight, Highlight::Pressed);
    // The normal state is drawn with the foreground, not the negative colour.
    let normal = resolved.pick(Kind::Close, State::Normal, 1.0).unwrap();
    assert_eq!(normal.highlight, Highlight::None);
    assert_eq!(resolved.tints.close_fill(normal.highlight, bg), None);
}

#[test]
fn gtk_assets_for_close_hover_and_pressed_are_drawn_unmodified() {
    let (fx, env) = Fixture::new(true);
    kde_gtk_config(&fx, "gtk-3.0");
    let resolved = resolve_env(&env).unwrap();
    let hover = resolved.pick(Kind::Close, State::Hover, 1.0).unwrap();
    let pressed = resolved.pick(Kind::Close, State::Active, 1.0).unwrap();
    assert!(pressed.asset.path.ends_with("titlebutton-close-active.png"));
    assert!(!hover.asset.symbolic);
    assert_eq!(
        (hover.highlight, pressed.highlight),
        (Highlight::None, Highlight::None)
    );
    // Only a hover image: it is reused for pressed, still with nothing drawn over it.
    let (fx2, env2) = Fixture::new(true);
    fx2.png("home/.config/gtk-3.0/a.png", [255, 255, 255, 255], 4);
    fx2.png("home/.config/gtk-3.0/h.png", [200, 0, 0, 255], 4);
    fx2.write(
        "home/.config/gtk-3.0/window_decorations.css",
        ".titlebar button.close, .titlebar button.minimize, .titlebar button.maximize { background-image: url(a.png) }\n\
         .titlebar button.close:hover { background-image: url(h.png) }",
    );
    let only_hover = resolve_env(&env2).unwrap();
    let pressed = only_hover.pick(Kind::Close, State::Active, 1.0).unwrap();
    assert!(pressed.asset.path.ends_with("h.png"));
    assert_eq!(pressed.highlight, Highlight::None);
}

/// A stroke-only 16 px SVG: a plus sign in `color` on transparency, like kde-gtk-config's.
fn stroke_svg(fx: &Fixture, relative: &str, color: &str) {
    fx.write(
        relative,
        format!(
            r#"<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><path d="M8 3v10M3 8h10" stroke="{color}" stroke-width="2" fill="none"/></svg>"#
        ),
    );
}

/// Breeze-style symbolic icons in the icon theme.
fn breeze_icons(fx: &Fixture) {
    fx.write("home/.config/kdeglobals", "[Icons]\nTheme=breeze\n");
    icon_theme(
        fx,
        "breeze",
        "[Icon Theme]\nDirectories=actions\n[actions]\nSize=16\nType=Fixed\n",
    );
    for name in ["minimize", "maximize", "restore", "close"] {
        fx.svg(
            &format!("usr/share/icons/breeze/actions/window-{name}-symbolic.svg"),
            "#000",
        );
    }
}

/// kde-gtk-config assets whose glyphs are `glyph`, with or without symbolic icons behind them.
fn glyph_theme(glyph: &str, icons: bool) -> (Fixture, Resolved) {
    let (fx, env) = Fixture::new(true);
    let mut css = String::new();
    for name in ["close", "minimize", "maximize"] {
        stroke_svg(
            &fx,
            &format!("home/.config/gtk-3.0/assets/{name}-normal.svg"),
            glyph,
        );
        css += &format!(
            ".titlebar button.titlebutton.{name} {{ background-image: url(\"assets/{name}-normal.svg\") }}\n"
        );
    }
    fx.write("home/.config/gtk-3.0/window_decorations.css", css);
    if icons {
        breeze_icons(&fx);
    }
    let resolved = resolve_env(&env).unwrap();
    assert_eq!(resolved.source, Source::KdeGtkConfig);
    (fx, resolved)
}

fn picked_symbolic(resolved: &Resolved, titlebar: Color32) -> Option<bool> {
    resolved
        .readable_pick(Kind::Close, State::Normal, 1.0, titlebar)
        .map(|p| p.asset.symbolic)
}

#[test]
fn a_light_glyph_on_a_light_title_bar_falls_back_to_the_symbolic_icon() {
    // Issue 71: `#e7e1e2` strokes (Breeze Dark's foreground) on Xuan's Light title bar.
    let (_fx, resolved) = glyph_theme("#e7e1e2", true);
    let light_bar = Color32::from_gray(235);
    let glyph = resolved
        .pick(Kind::Close, State::Normal, 1.0)
        .unwrap()
        .asset
        .glyph
        .unwrap();
    assert_eq!(glyph.background, None);
    assert!(glyph.color.iter().all(|c| (0xe0..=0xe8).contains(c)));
    assert!(!glyph.readable_on(light_bar));
    assert_eq!(picked_symbolic(&resolved, light_bar), Some(true));
    for kind in [Kind::Minimize, Kind::Maximize] {
        let pick = resolved
            .readable_pick(kind, State::Hover, 1.0, light_bar)
            .unwrap();
        assert!(pick.asset.symbolic);
        assert_eq!(pick.highlight, Highlight::Hover);
    }
}

#[test]
fn readable_images_are_kept_and_the_opposite_pairing_falls_back() {
    let (_fx, light_glyph) = glyph_theme("#e7e1e2", true);
    assert_eq!(
        picked_symbolic(&light_glyph, Color32::from_gray(45)),
        Some(false)
    );
    let (_fx, dark_glyph) = glyph_theme("#232629", true);
    assert_eq!(
        picked_symbolic(&dark_glyph, Color32::from_gray(235)),
        Some(false)
    );
    assert_eq!(
        picked_symbolic(&dark_glyph, Color32::from_gray(45)),
        Some(true)
    );
}

#[test]
fn without_symbolic_icons_an_unreadable_image_leaves_the_built_in_glyphs() {
    let (_fx, resolved) = glyph_theme("#e7e1e2", false);
    let pick =
        |bar| resolved.readable_pick(Kind::Close, State::Normal, 1.0, Color32::from_gray(bar));
    assert!(pick(235).is_none());
    assert!(pick(45).is_some());
}

#[test]
fn an_image_with_its_own_background_is_judged_against_that_background() {
    // Breeze's close button: a red disc with a white cross, transparent in the corners.
    let (fx, env) = Fixture::new(true);
    fx.write(
        "home/.config/gtk-3.0/assets/close.svg",
        r##"<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><circle cx="8" cy="8" r="8" fill="#da4453"/><path d="M5 5l6 6M11 5l-6 6" stroke="#ffffff" stroke-width="2"/></svg>"##,
    );
    for name in ["minimize", "maximize"] {
        stroke_svg(
            &fx,
            &format!("home/.config/gtk-3.0/assets/{name}.svg"),
            "#000",
        );
    }
    fx.write(
        "home/.config/gtk-3.0/window_decorations.css",
        ".titlebar button.titlebutton.close { background-image: url(\"assets/close.svg\") }\n\
         .titlebar button.titlebutton.minimize { background-image: url(\"assets/minimize.svg\") }\n\
         .titlebar button.titlebutton.maximize { background-image: url(\"assets/maximize.svg\") }\n",
    );
    let resolved = resolve_env(&env).unwrap();
    let glyph = resolved
        .pick(Kind::Close, State::Normal, 1.0)
        .unwrap()
        .asset
        .glyph
        .unwrap();
    let [r, g, b] = glyph.background.expect("the disc is the background");
    assert!(r > 200 && g < 100 && b < 100, "{r} {g} {b}");
    assert!(glyph.color.iter().all(|&c| c > 200), "{:?}", glyph.color);
    // White on red reads on any bar, so the image stays.
    for bar in [Color32::from_gray(235), Color32::from_gray(45)] {
        assert_eq!(picked_symbolic(&resolved, bar), Some(false));
    }
}

#[test]
fn symbolic_icons_still_go_through_the_tint_contrast_check() {
    let (fx, env) = Fixture::new(true);
    breeze_icons(&fx);
    fx.write(
        "home/.config/kdeglobals",
        "[Icons]\nTheme=breeze\n[Colors:Header]\nForegroundNormal=#e7e1e2\n",
    );
    let resolved = resolve_env(&env).unwrap();
    // Symbolic icons carry no measured glyph and are never swapped.
    let pick = resolved
        .readable_pick(Kind::Close, State::Normal, 1.0, Color32::from_gray(235))
        .unwrap();
    assert!(pick.asset.symbolic && pick.asset.glyph.is_none());
    // The desktop's light foreground is dropped on a light bar, kept on a dark one.
    let fallback = Color32::from_gray(20);
    let tint = |bar| {
        resolved
            .tints
            .color(false, Color32::from_gray(bar), fallback)
    };
    assert_eq!(tint(235), fallback);
    assert_eq!(tint(45), Color32::from_rgb(0xe7, 0xe1, 0xe2));
}
